const wordList = [
      { word: "wand", hint: "A magical tool used by wizards and witches." },
      { word: "spell", hint: "A magical incantation that produces a magical effect." },
      { word: "broom", hint: "Used for flying in the wizarding world." },
      { word: "snitch", hint: "A tiny golden ball used in Quidditch." },
      { word: "owl", hint: "A magical bird used for delivering mail in the wizarding world." },

      { word: "potion", hint: "A magical liquid with various effects." },
      { word: "cloak", hint: "A magical garment that grants invisibility." },
      { word: "house", hint: "The four divisions at Hogwarts School of Witchcraft and Wizardry." },
      { word: "cauldron", hint: "A large metal pot used for brewing potions." },
      { word: "dragon", hint: "A mythical creature with wings and the ability to breathe fire." },

      { word: "wandmaker", hint: "A person who crafts wands." },
      { word: "phoenix", hint: "A magnificent bird that rises from its ashes." },
      { word: "patronus", hint: "A magical guardian that protects against Dementors." },
      { word: "gringotts", hint: "The wizarding bank in Diagon Alley." },
      { word: "marauders", hint: "A group of trouble-making students at Hogwarts." },

      { word: "horcrux", hint: "An object used to store a piece of a dark wizard's soul." },
      { word: "animagus", hint: "A witch or wizard who can transform into an animal at will." },
      { word: "apparate", hint: "Magical form of teleportation used by witches and wizards." },
      { word: "basilisk", hint: "A giant serpent that can kill with its gaze." },
      { word: "portkey", hint: "An object enchanted to transport people to a specific location." },

      { word: "bezoar", hint: "A stone taken from the stomach of a goat, used as an antidote." },
      { word: "azkaban", hint: "The wizarding prison guarded by Dementors." },
      { word: "deathlyhallows", hint: "Three powerful magical objects: the Elder Wand, Resurrection Stone, and Invisibility Cloak." },
      { word: "dementor", hint: "A dark creature that feeds on happy emotions." },
      { word: "polyjuice", hint: "A potion that allows a person to assume the appearance of someone else." },
      { word: "accio", hint: "A spell used to summon objects to the caster." },
      { word: "obliviate", hint: "A memory-erasing charm." },
      { word: "parseltongue", hint: "The ability to speak to snakes." },
      { word: "legilimens", hint: "A spell that allows the caster to enter another person's mind." },
      { word: "sectumsempra", hint: "A dangerous cutting curse invented by Severus Snape." },
      { word: "boggart", hint: "A shapeshifting creature that takes the form of its viewer's worst fear." },
      { word: "fawkes", hint: "Dumbledore's loyal phoenix companion." },
      { word: "lestrange", hint: "A notorious dark witch family." },
      { word: "remembrall", hint: "A magical glass ball that helps one remember forgotten things." },
      { word: "stupefy", hint: "A stunning spell used to immobilize opponents." },
      { word: "triwizard", hint: "A magical tournament held between three wizarding schools." },
      { word: "parselmouth", hint: "A person who can speak Parseltongue." },
      { word: "flooNetwork", hint: "A system of fireplaces for magical transportation." },
      { word: "azkaban", hint: "The wizarding prison guarded by Dementors." },
      { word: "veela", hint: "Enchanting, semi-human magical beings." },
      { word: "occlumency", hint: "The art of closing one's mind to prevent intrusion." },
      { word: "quibbler", hint: "A wizarding tabloid published by Xenophilius Lovegood." },
      { word: "thestrals", hint: "Winged, skeletal horses that can only be seen by those who have witnessed death." },
      { word: "halfbloodprince", hint: "A mysterious potions book with handwritten notes by a previous owner." },
      { word: "hogwartsexpress", hint: "The train that takes students to Hogwarts School of Witchcraft and Wizardry." },
      { word: "horaceslughorn", hint: "A former Hogwarts potions master and head of Slytherin House." },
      { word: "wizengamot", hint: "The highest court in wizarding Britain." },
      { word: "lumos", hint: "A spell used to produce light from the tip of a wand." },
      { word: "apparition", hint: "Magical form of teleportation used by witches and wizards." },
      { word: "elderwand", hint: "One of the Deathly Hallows, considered the most powerful wand in existence." },
    
  ];